<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
	<title>404 Page</title>
</head>
<body>
    <section class="section">
        <h1 class="title">404 - ${errMsg}</h1>
        <p class="subtitle"><a href="/file-explorer?dir=${baseDirPath}">Return to root</a></p>
    </section>
</body>
</html> 