<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
<#--    <title>${meta.title}</title>-->
</head>
<body>
<#--    <section class="section">-->
<#--        <h1 class="title">${meta.title}</h1>-->
<#--        <p class="subtitle">${meta.description}</p>-->
<#--    </section>-->

<#--    <section class="section pt-0">-->

<#--        <nav class="breadcrumb">-->
<#--            <ul>-->
<#--                <li><a href="/?dir=${content.baseDir.getPath()}">$</a></li>-->
<#--                <#list content.breadCrumb as e>-->
<#--                    <li><a href="/?dir=${e.getPath()}">${e.getName()}</a></li>-->
<#--                </#list>-->
<#--            </ul>-->
<#--        </nav>-->

<#--        <table class="table is-bordered is-hoverable">-->
<#--            <thead>-->
<#--            <tr>-->
<#--                <th>fileName</th>-->
<#--                <th>accessAttributes</th>-->
<#--                <th>size</th>-->
<#--                <th>lastModified</th>-->
<#--            </tr>-->
<#--            </thead>-->
<#--            <tbody>-->
<#--            <#list content.files as file>-->
<#--                <tr>-->
<#--                    <th><a href="/?dir=${file.getPath()}">${file.getName()}</a></th>-->
<#--                    <td>${file.getAccessAttributes()}</td>-->
<#--                    <td>${file.getSize()}</td>-->
<#--                    <td>${file.getLastModified()}</td>-->
<#--                </tr>-->
<#--            </#list>-->
<#--            </tbody>-->
<#--        </table>-->
<#--    </section>-->
</body>
</html>